---
title: "Global plate model choice impacts reconstructions of the latitudinal biodiversity gradient"
author:
  - "---"
  - Lewis A. Jones^1^, Bethany J. Allen^2,3^, William Gearty^4^, and Lucas Buffan^4^
  - "---"
  - "^1^Grupo de Ecoloxía Animal, Departamento de Ecoloxía e Bioloxía Animal, Universidade de Vigo, 36310 Vigo, Spain."
  - "^2^Department of Biosystems Science and Engineering, ETH Zürich, 4058 Basel, Switzerland."
  - "^3^Computational Evolution Group, Swiss Institute of Bioinformatics, 1015 Lausanne, Switzerland."
  - "^4^Division of Paleontology, American Museum of Natural History, New York, NY, 10024 USA."
  - "^5^Département de Biologie, École Normale Supérieure de Lyon, Université Claude Bernard Lyon 1, 69342 Lyon Cedex 07, France."
  - "---"
  - "**All authors contributed equally to this work**"
  - "**Corresponding author:** LewisAlan.Jones@uvigo.es"
abstract: \newpage Abstract
format:
  docx:
    reference-doc: template.docx
    highlight-style: github
    fig-dpi: 900
  pdf:
    documentclass: scrartcl
    papersize: letter
    geometry:
      - top=25.4mm
      - bottom=25.4mm
      - left=25.4mm
      - right=25.4mm
      - heightrounded
bibliography: references.bib
csl: biology-letters.csl
editor: 
  markdown: 
    wrap: 72
---

Here goes the abstract...

# Keywords

Latitudinal biodiversity gradient, marine invertebrates, macroecology,
global plate model, palaeogeographic uncertainty

\newpage

# Introduction (600 words)

Today, species richness decreases from the tropics to the poles. This
phenomenon is known as the latitudinal biodiversity gradient (LBG), and
is one of Earth's longest recognised macroecological patterns
[@humboldt1807; @willig2003; @hillebrand2004; @mannion2014]. While
observed across numerous taxonomic groups in the terrestrial
[@willig2003; @hillebrand2004] and marine realm today [@roy2000;
@valentine2015], the fossil record suggests this broadly unimodal
gradient was not always present, with flattened and bimodal gradients
observed across a range of taxonomic groups at various points in Earth's
geological history [e.g. @rose2011; @mannion2012; @yasuhara2012;
@powell2015; @nicholson2016; @allen2020; @song2020; @zhang2022;
@fenton2023]. Several studies have demonstrated that tropical peaks and
poleward declines in taxonomic richness are restricted to the last 30
million years (Myr), and intervals of the Palaeozoic, when cool icehouse
climatic regimes persisted [e.g. @mannion2014; @fenton2016; @marcot2016;
@kroger2018; @fenton2023]. Conversely, during intervals of warmer
climatic conditions (i.e. greenhouse and interglacial periods), various
taxonomic groups have exhibited flattened LBGs, or even temperate peaks
in biodiversity [e.g. @mannion2012; @yasuhara2012; @kiessling2012;
@nicholson2016; @allen2020; @song2020; @dunne2020]. However, recent work
suggests that the recognition of different types of LBG in deep time is
limited by incomplete and heterogeneous spatial sampling [@jones2021].

When examining the LBG in the present day, neontologists use the direct
geographic distribution of organisms. However, palaeobiologists must
contend with the shift of the continents over geological timescales; the
geographic location of a fossil occurrence on the Earth's surface today
does not necessarily represent its location *in vivo*. Consequently,
reconstructing the past geographic distribution of fossil occurrences is
fundamental to reconstructing the LBG in deep time. To do so,
palaeobiologists routinely use what is known as Global Plate
Models--sometimes also called 'palaeorotation models' or 'plate rotation
models'--[@brocklehurst2017; @kroger2018; @dunne2020; @antell2020;
@boag2021; @zhang2022]. These models aim to reconstruct the tectonic
evolution of the Earth by modelling the motion of the continental--and
sometimes marine--plates across its surface through geological time.
Many of these Global Plate Models exist [e.g. @seton2012; @wright2013;
@scotese2018; @merdith2021], varying in the way they define the
geological boundaries of continents and how they rotate them through
time, having consequence for how fossil occurrences might be
palaeogeographically reconstructed [@seton2023]. However--to date--few
palaeobiological studies (though see ref. [@boddy2022; @jones2022]) have
considered how different Global Plate Models might influence
reconstructions of the latitudinal distribution of fossil occurrence.

Here, we test whether Global Plate Model choice influences the
recognition of 'unimodal-type' latitudinal biodiversity gradients
throughout the Phanerozoic (the last 540 million years). To do so, we
reconstruct the palaeogeographic distribution of fossil occurrences for
five major marine invertebrate groups using data from The Paleobiology
Database and three Global Plate Models. Subsequently, we reconstruct the
latitudinal biodiversity gradient using coverage-based rarefaction--a
common sampling-standardisation approach--and quantify the strength of
the gradient through time and the variability between Global Plate
Models. We hypothesis that reconstructions of the latitudinal
biodiversity gradient are more sensitive to plate rotation model choice
with age of rotation.

# Materials and Methods (600 words)

## Occurrence data

<!-- Download data -->

`r ddate <- format(file.info("../data/raw/pbdb_data.RDS")$ctime, format = "%B %d %Y")`
<!-- Palaeoverse version -->
`r palaeoverse_ver <- packageVersion("palaeoverse")`
<!-- Analysis options --> `r source("../R/options.R")`
<!-- Number of occurrences -->
`r n_occ <- format(nrow(readRDS("../data/processed/pbdb_data.RDS")), big.mark = ",")`
<!-- Number of collections -->
`r n_coll <- format(length(unique(readRDS("../data/processed/pbdb_data.RDS")$collection_no)), big.mark = ",")`

We downloaded Fortunian--Piacenzian (541--0 Ma) fossil occurrence data
from The Paleobiology Database (PBDB; <https://paleobiodb.org/>) for
five major marine invertebrate groups (Bivalvia, Brachiopoda,
Cephalopoda, Gastropoda, Trilobita) on `r ddate`. Fossil occurrence data
were downloaded using the PBDB API service and were restricted to marine
environments, valid taxa and regular preservation (i.e. excluding form
taxa and ichnotaxa). Occurrence data were subsequently binned into
stratigraphic time bins following the Geological Timescale 2020
[@gradstein2020]. To do so, we used the bin_time() function from the
palaeoverse R package ver. `r palaeoverse_ver` using the 'majority'
approach [@jones2023]. Subsequently, we removed all occurrences with
less than `r params$threshold`% of their age range covered by their
assigned temporal bin. After data preparation, the occurrence dataset
contained `r n_occ` occurrences from `r n_coll` collections.

## Palaeogeographic reconstruction and binning

To reconstruct the palaeogeographic distribution of fossil occurrences,
we used occurrences' present-day coordinates and midpoint age from
assigned temporal bins with three Global Plate Models: PALEOMAP
[@scotese2018], GOLONKA [@wright2013], and MERDITH2021 [@merdith2021].
Palaeogeographic reconstructions were generated using the GPlates Web
Service (<https://gwsdoc.gplates.org>) via the palaeorotate() function
in palaeoverse ver. `r palaeoverse_ver` [@jones2023]. Subsequently, for
each Global Plate Model, fossil occurrences were binned into one of
twelve equal-area latitudinal bins (assuming a regular spheroid Earth
model with a radius of \~6,371 km), using the estimated palaeolatitudes
([@tbl-bins]).

```{r}
#| label: tbl-bins
#| tbl-cap: "Equal-area latitudinal bins used in this study. Bins are generated assumming a regular spheroid Earth model with a mean radius of ~6,371 km."
#| tbl-colwidths: [100, 100, 100, 100, 100, 100]
#| echo: false
library(knitr)
df <- readRDS("../data/lat_bins.RDS")
df$area <- signif(x = df$area, digits = 3)
df$area_prop <- round(df$area_prop, 3)
colnames(df) <- c("Bin", "Maximum", "Midpoint", "Minimum", "Area (m^2^)", "Proportion of Area")
options(scipen = 0)
kable(df)
```

## Quantifying the latitudinal biodiveristy gradient

-   Metrics used to quantify the gradient

# Results (600 words)

-   Summary of reconstructions (could all points be reconstructed for
    each model?)
-   Summary of results from metrics, do different gradients emerge?

# Discussion (700 words)

-   Recap on importance of GPMs for deep time macroecology?
-   What have we shown?
-   Are some times or areas more problematic than others?
-   Importance for other fields beyond palaeobiology?
-   Consider importance of GPM choice in future work... or not?

# Data accessibility

# Authors' contributions

# Funding

# Acknowledgements

# References
