---
title: "Supplementary Material: Global plate model choice impacts reconstructions of the latitudinal biodiversity gradient"
author:
  - "---"
  - Lewis A. Jones^1^, Bethany J. Allen^2,3^, William Gearty^4^, and Lucas Buffan^4^
  - "---"
  - "^1^Grupo de Ecoloxía Animal, Departamento de Ecoloxía e Bioloxía Animal, Universidade de Vigo, 36310 Vigo, Spain."
  - "^2^Department of Biosystems Science and Engineering, ETH Zürich, 4058 Basel, Switzerland."
  - "^3^Computational Evolution Group, Swiss Institute of Bioinformatics, 1015 Lausanne, Switzerland."
  - "^4^Smithsonian National Museum of Natural History, Department of Paleobiology, Washington, DC, 20560, USA"
  - "^5^Département de Biologie, École Normale Supérieure de Lyon, Université Claude Bernard Lyon 1, 69342 Lyon Cedex 07, France."
  - "---"
  - "**Corresponding author:** LewisAlan.Jones@uvigo.es"
format:
  docx:
    reference-doc: template.docx
    highlight-style: github
    fig-dpi: 900
  pdf:
    documentclass: scrartcl
    papersize: letter
    geometry:
      - top=25.4mm
      - bottom=25.4mm
      - left=25.4mm
      - right=25.4mm
      - heightrounded
bibliography: references.bib
csl: biology-letters.csl
---

# Supplementary Text
## Additional details about the Global Plate Models we chose for this study, from a palaeobiological perspective

<<<<<<< Updated upstream
## Additional details about the Global Plate Models we chose for this study, from a palaeobiological perspective

Here, we test the sensitivity of deep-time Latitudinal Biodiversity Gradient reconstructions to the use of different Global Plate Models (GPMs).

GPMs use the Euler Rotation Theorem to reconstruct the motion of tectonic plates on a sphere-like structure---the Earth. Based on a compilation of geological data (see [@seton2023] for an extensive review), a GPM divides tectonic plates into smaller sub-units that will move independently. It therefore takes two main inputs: (1) a set of tectonic elements and (2) a tree-like structured framework in which these elements moved throughout geological times relatively to a fixed anchor, called reference frame [@seton2023; @verard2019; @ross1988]. Two classes of GPMs exist. On the one hand, 'Continental drift' models aim at reconstructing the motion of present-day continental areas--discontinuous subset of rigid plates--as if they were 'floating' on the mantle [e.g. @wright2013; @scotese2018]. On the other hand 'full-plate' model describe in detail how plate borders have evolved through geological times [e.g. @gurnis2012; @seton2012], therefore tackling the issue from a more mechanistic perspective. Latest models of the latter class also allow for plate deformation while moving [e.g. @gurnis2018; @muller2019].
=======
Here, we test the sensitivity of deep-time Latitudinal Biodiversity Gradient reconstructions to the use of different Global Plate Models (GPMs).

GPMs use the Euler Rotation Theorem to reconstruct the motion of tectonic plates on a sphere-like structure–-the Earth. Based on a compilation of geological data (see [@seton2023] for an extensive review), a GPM divides tectonic plates into smaller sub-units that will move independently. It therefore takes two main inputs: (1) a set of tectonic elements and (2) a tree-like structured framework in which these elements moved throughout geological times relatively to a fixed anchor, called reference frame [@seton2023; @verard_plate_2019; @ross_hierarchical_1988]. Two classes of GPMs exist. On the one hand, ‘Continental drift’ models aim at reconstructing the motion of present-day continental areas--discontinuous subset of rigid plates--as if they were 'floating' on the mantle [e.g. @wright2013; @scotese2018]. On the other hand ‘full-plates’ model describe in detail how plate borders have evolved through geological times [e.g. @gurnis_plate_2012; @seton2012], therefore tackling the issue from a more mechanistic perspective. Latest models of the latter class also allow for plate deformation while moving [e.g. @gurnis2018global; @muller2019global].

Many of the GPMs released so far are freely available via open-source platforms, such as GPlates [@boyden2011next]. However, in the face of such an easy access, it becomes important for users to bear in mind that GPMs have been developed for a variety of purposes, and are not necessarily showing the same thing altogether. In particular, models using a mantle reference frame  [e.g. @muller2019global; @young2019global] are constraining tectonic plate motion to the mantle. While perfectly suited to study the plate-mantle system, anchoring plate motion to the mantle removes additional factors responsible for plate motion (such as the rotation of the Earth) [@seton2023]. The palaeocoordinate estimates they produce are therefore naturally biased. Hence, models using a mantle reference frame should not be used to get palaeocoordinates, which is most of the time why these models are used in palaeobiology. Rather, people interested in actual palaeocoorinate estimates should favour the use of models using a palaeomagnetic reference frame
>>>>>>> Stashed changes

Many of the GPMs released so far are freely available via open-source platforms, such as GPlates [@boyden2011]. However, in the face of such an easy access, it becomes important for users to bear in mind that GPMs have been developed for a variety of purposes, and are not necessarily showing the same thing altogether. In particular, models using a mantle reference frame [e.g. @muller2019; @young2019] are constraining tectonic plate motion to the mantle. While perfectly suited to study the plate-mantle system, anchoring plate motion to the mantle removes additional factors responsible for plate motion (such as the rotation of the Earth) [@seton2023]. The palaeocoordinate estimates they produce are therefore naturally biased. Hence, models using a mantle reference frame should not be used to get palaeocoordinates, which is most of the time why these models are used in palaeobiology. Rather, people interested in actual palaeocoorinate estimates should favour the use of models using a palaeomagnetic reference frame, as palaeomagnetic data provide actual constraints for palaeolatitude [@seton2023]. This said, one should notice that this does not apply to palaeolongitude, which is harder to constrain, especially in deep time [@verard2019; @seton2023].

For our study, we therefore chose three GPMs using a palaeomagnetic reference frame, either among the most widely used in palaeobiology (PALEOMAP [@scotese2018] and GOLONKA [@wright2013]) or among the cutting-edge of the field (MERDITH2021 [@merdith2021]). The GOLONKA model comes from an earlier version of PALEOMAP. While the GOLONKA spans the entire Phanerozoic, the latest version of PALEOMAP (that we are using here) goes up to 750 Ma. As for it, the MERDITH2021 provides reconstructions for the last 1000 Ma. It comes from the combination of models spanning the Neoproterozoic [@merdith2017], the beginning of the Phanerozoic until Early Devonian [@domeier2016; @domeier2019] and the last 410 Ma [@young2019].

# References

# Supplementary Tables

# Supplementary Figures
